title: Stéphane D.  # Add a space after the period

logo: ghost.png # Use a relative path to logo image 

description: SRE

show_downloads: true # Fix spelling

# theme: jekyll-theme-minimal 
remote_theme: pages-themes/merlot@v0.2.0
plugins:
  - jekyll-seo-tag # Add SEO plugin
  - jekyll-remote-theme 


#google_site_verification: "nE-yBDoWCj5TcTXXNcRBPPiJZxpC6pw5dEdeRo6kTCk" # Verify ownership through Search Console  

#email: stephane.duboze@gmail.com # Allow visitors to contact you
