title: Stéphane D.  

logo: flower.png 

description: SRE

description: DevSecOps Engineer / SRE 
mycontact : 'My email: stephane857@live.fr'
show_downloads: true

theme: jekyll-theme-minimal
#remote_theme: hydecorp/hydejack@v9.1.6
plugins:
#  - jekyll-remote-theme 
#  - jekyll-include-cache
   - jekyll-seo-tag
email: stephane857@live.fr
