title: Stéphane D.  # Add a space after the period

logo: flower.png # Use a relative path to logo image 

description: SRE

description: DevSecOps Engineer / SRE 
mycontact : 'My email: stephane857@live.fr'
show_downloads: true # Fix spelling

theme: jekyll-theme-minimal
#remote_theme: hydecorp/hydejack@v9.1.6
plugins:
#  - jekyll-remote-theme 
#  - jekyll-include-cache
   - jekyll-seo-tag
#email: stephane.duboze@gmail.com # Allow visitors to contact you
