title: Stéphane D.  # Add a space after the period

logo: flower.gif # Use a relative path to logo image 

description: SRE

show_downloads: true # Fix spelling

theme: jekyll-theme-minimal
#remote_theme: hydecorp/hydejack@v9.1.6
plugins:
#  - jekyll-remote-theme 
#  - jekyll-include-cache

#email: stephane.duboze@gmail.com # Allow visitors to contact you
